//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumnos()
        {
            this.Calificaciones = new HashSet<Calificaciones>();
        }
    
        public int ID_Alumno { get; set; }
        public string Nombre { get; set; }
        public string ApePat { get; set; }
        public string ApeMat { get; set; }
        public string Matricula { get; set; }
        public string Curp { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Sexo { get; set; }
        public string Foto_Url { get; set; }
        public string Direccion { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Turno { get; set; }
        public Nullable<int> Semestre_ID { get; set; }
    
        public virtual Semestres Semestres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificaciones> Calificaciones { get; set; }
    }
}
